// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace OffCenter.iOS
{
	public partial class BeaconTableViewCell : UITableViewCell
	{
		public BeaconTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
