// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace OffCenter.iOS
{
	public partial class LoginNavigationController : UINavigationController
	{
		public LoginNavigationController (IntPtr handle) : base (handle)
		{
		}
	}
}
