// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AndroidProject
    {
        /// <summary>
        /// Initializes a new instance of the AndroidProject class.
        /// </summary>
        public AndroidProject() { }

        /// <summary>
        /// Initializes a new instance of the AndroidProject class.
        /// </summary>
        public AndroidProject(IList<AndroidModule> androidModules, string gradleWrapperPath = default(string))
        {
            AndroidModules = androidModules;
            GradleWrapperPath = gradleWrapperPath;
        }

        /// <summary>
        /// Android Gradle modules
        /// </summary>
        [JsonProperty(PropertyName = "androidModules")]
        public IList<AndroidModule> AndroidModules { get; set; }

        /// <summary>
        /// The path of the Gradle wrapper
        /// </summary>
        [JsonProperty(PropertyName = "gradleWrapperPath")]
        public string GradleWrapperPath { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (AndroidModules == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AndroidModules");
            }
            if (this.AndroidModules != null)
            {
                foreach (var element in this.AndroidModules)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
