// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ApiTokensGetResponse
    {
        /// <summary>
        /// Initializes a new instance of the ApiTokensGetResponse class.
        /// </summary>
        public ApiTokensGetResponse() { }

        /// <summary>
        /// Initializes a new instance of the ApiTokensGetResponse class.
        /// </summary>
        public ApiTokensGetResponse(string id, string createdAt, string description = default(string))
        {
            Id = id;
            Description = description;
            CreatedAt = createdAt;
        }

        /// <summary>
        /// The unique id (UUID) of the api token
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// The description of the token
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// The creation time
        /// </summary>
        [JsonProperty(PropertyName = "created_at")]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (CreatedAt == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "CreatedAt");
            }
        }
    }
}
