// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ApiTokensCreateRequest
    {
        /// <summary>
        /// Initializes a new instance of the ApiTokensCreateRequest class.
        /// </summary>
        public ApiTokensCreateRequest() { }

        /// <summary>
        /// Initializes a new instance of the ApiTokensCreateRequest class.
        /// </summary>
        public ApiTokensCreateRequest(string description = default(string))
        {
            Description = description;
        }

        /// <summary>
        /// The description of the token
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
