// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AppInvitationDetailResponse
    {
        /// <summary>
        /// Initializes a new instance of the AppInvitationDetailResponse
        /// class.
        /// </summary>
        public AppInvitationDetailResponse() { }

        /// <summary>
        /// Initializes a new instance of the AppInvitationDetailResponse
        /// class.
        /// </summary>
        public AppInvitationDetailResponse(string id, string email, bool isExistingUser, UserProfileResponse invitedBy, string inviteType, AppResponse app)
        {
            Id = id;
            Email = email;
            IsExistingUser = isExistingUser;
            InvitedBy = invitedBy;
            InviteType = inviteType;
            App = app;
        }

        /// <summary>
        /// The unique ID (UUID) of the invitation
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// The email address of the invited user
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Indicates whether the invited user already exists
        /// </summary>
        [JsonProperty(PropertyName = "is_existing_user")]
        public bool IsExistingUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "invited_by")]
        public UserProfileResponse InvitedBy { get; set; }

        /// <summary>
        /// The invitation type. Possible values include: 'developer', 'tester'
        /// </summary>
        [JsonProperty(PropertyName = "invite_type")]
        public string InviteType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "app")]
        public AppResponse App { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (Email == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Email");
            }
            if (InvitedBy == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "InvitedBy");
            }
            if (InviteType == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "InviteType");
            }
            if (App == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "App");
            }
            if (this.InvitedBy != null)
            {
                this.InvitedBy.Validate();
            }
            if (this.App != null)
            {
                this.App.Validate();
            }
        }
    }
}
