// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The branch build configuration for each toolset
    /// </summary>
    public partial class BranchConfigurationToolsets
    {
        /// <summary>
        /// Initializes a new instance of the BranchConfigurationToolsets
        /// class.
        /// </summary>
        public BranchConfigurationToolsets() { }

        /// <summary>
        /// Initializes a new instance of the BranchConfigurationToolsets
        /// class.
        /// </summary>
        public BranchConfigurationToolsets(XcodeBranchConfigurationProperties xcode = default(XcodeBranchConfigurationProperties), JavaScriptBranchConfigurationProperties javascript = default(JavaScriptBranchConfigurationProperties), XamarinBranchConfigurationProperties xamarin = default(XamarinBranchConfigurationProperties), AndroidBranchConfigurationProperties android = default(AndroidBranchConfigurationProperties))
        {
            Xcode = xcode;
            Javascript = javascript;
            Xamarin = xamarin;
            Android = android;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xcode")]
        public XcodeBranchConfigurationProperties Xcode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "javascript")]
        public JavaScriptBranchConfigurationProperties Javascript { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xamarin")]
        public XamarinBranchConfigurationProperties Xamarin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "android")]
        public AndroidBranchConfigurationProperties Android { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Xcode != null)
            {
                this.Xcode.Validate();
            }
            if (this.Javascript != null)
            {
                this.Javascript.Validate();
            }
            if (this.Xamarin != null)
            {
                this.Xamarin.Validate();
            }
            if (this.Android != null)
            {
                this.Android.Validate();
            }
        }
    }
}
