// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BuildPatch
    {
        /// <summary>
        /// Initializes a new instance of the BuildPatch class.
        /// </summary>
        public BuildPatch() { }

        /// <summary>
        /// Initializes a new instance of the BuildPatch class.
        /// </summary>
        public BuildPatch(string status = default(string))
        {
            Status = status;
        }

        /// <summary>
        /// The build status
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
