// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CrashFreeDevicePercentages
    {
        /// <summary>
        /// Initializes a new instance of the CrashFreeDevicePercentages class.
        /// </summary>
        public CrashFreeDevicePercentages() { }

        /// <summary>
        /// Initializes a new instance of the CrashFreeDevicePercentages class.
        /// </summary>
        public CrashFreeDevicePercentages(long? averagePercentage = default(long?), IList<DateTimePercentages> dailyPercentages = default(IList<DateTimePercentages>))
        {
            AveragePercentage = averagePercentage;
            DailyPercentages = dailyPercentages;
        }

        /// <summary>
        /// Average percentage
        /// </summary>
        [JsonProperty(PropertyName = "average_percentage")]
        public long? AveragePercentage { get; set; }

        /// <summary>
        /// The crash-free percentage per day.
        /// </summary>
        [JsonProperty(PropertyName = "daily_percentages")]
        public IList<DateTimePercentages> DailyPercentages { get; set; }

    }
}
