// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CrashGroupOperatingSystem
    {
        /// <summary>
        /// Initializes a new instance of the CrashGroupOperatingSystem class.
        /// </summary>
        public CrashGroupOperatingSystem() { }

        /// <summary>
        /// Initializes a new instance of the CrashGroupOperatingSystem class.
        /// </summary>
        public CrashGroupOperatingSystem(string operatingSystemName = default(string), long? crashCount = default(long?))
        {
            OperatingSystemName = operatingSystemName;
            CrashCount = crashCount;
        }

        /// <summary>
        /// OS name
        /// </summary>
        [JsonProperty(PropertyName = "operating_system_name")]
        public string OperatingSystemName { get; set; }

        /// <summary>
        /// count of OS
        /// </summary>
        [JsonProperty(PropertyName = "crash_count")]
        public long? CrashCount { get; set; }

    }
}
