// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CrashGroupAndVersion
    {
        /// <summary>
        /// Initializes a new instance of the CrashGroupAndVersion class.
        /// </summary>
        public CrashGroupAndVersion() { }

        /// <summary>
        /// Initializes a new instance of the CrashGroupAndVersion class.
        /// </summary>
        public CrashGroupAndVersion(string crashGroupId = default(string), string appVersion = default(string))
        {
            CrashGroupId = crashGroupId;
            AppVersion = appVersion;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crash_group_id")]
        public string CrashGroupId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "app_version")]
        public string AppVersion { get; set; }

    }
}
