// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CrashGroupModels
    {
        /// <summary>
        /// Initializes a new instance of the CrashGroupModels class.
        /// </summary>
        public CrashGroupModels() { }

        /// <summary>
        /// Initializes a new instance of the CrashGroupModels class.
        /// </summary>
        public CrashGroupModels(long? crashCount = default(long?), IList<CrashGroupModel> models = default(IList<CrashGroupModel>))
        {
            CrashCount = crashCount;
            Models = models;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crash_count")]
        public long? CrashCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "models")]
        public IList<CrashGroupModel> Models { get; set; }

    }
}
