// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CrashGroups
    {
        /// <summary>
        /// Initializes a new instance of the CrashGroups class.
        /// </summary>
        public CrashGroups() { }

        /// <summary>
        /// Initializes a new instance of the CrashGroups class.
        /// </summary>
        public CrashGroups(IList<CrashGroupAndVersion> crashGroupsProperty)
        {
            CrashGroupsProperty = crashGroupsProperty;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "crash_groups")]
        public IList<CrashGroupAndVersion> CrashGroupsProperty { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (CrashGroupsProperty == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "CrashGroupsProperty");
            }
            if (this.CrashGroupsProperty != null)
            {
                if (this.CrashGroupsProperty.Count < 1)
                {
                    throw new ValidationException(ValidationRules.MinItems, "CrashGroupsProperty", 1);
                }
            }
        }
    }
}
