// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DateTimeDecimalCounts
    {
        /// <summary>
        /// Initializes a new instance of the DateTimeDecimalCounts class.
        /// </summary>
        public DateTimeDecimalCounts() { }

        /// <summary>
        /// Initializes a new instance of the DateTimeDecimalCounts class.
        /// </summary>
        public DateTimeDecimalCounts(string datetime = default(string), double? count = default(double?))
        {
            Datetime = datetime;
            Count = count;
        }

        /// <summary>
        /// the ISO 8601 datetime
        /// </summary>
        [JsonProperty(PropertyName = "datetime")]
        public string Datetime { get; set; }

        /// <summary>
        /// decimal count of the object
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public double? Count { get; set; }

    }
}
