// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DateTimePercentages
    {
        /// <summary>
        /// Initializes a new instance of the DateTimePercentages class.
        /// </summary>
        public DateTimePercentages() { }

        /// <summary>
        /// Initializes a new instance of the DateTimePercentages class.
        /// </summary>
        public DateTimePercentages(string datetime = default(string), double? percentage = default(double?))
        {
            Datetime = datetime;
            Percentage = percentage;
        }

        /// <summary>
        /// the ISO 8601 datetime
        /// </summary>
        [JsonProperty(PropertyName = "datetime")]
        public string Datetime { get; set; }

        /// <summary>
        /// percentage of the object
        /// </summary>
        [JsonProperty(PropertyName = "percentage")]
        public double? Percentage { get; set; }

    }
}
