// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Short ID for a list of device IDs
    /// </summary>
    public partial class DeviceSelection
    {
        /// <summary>
        /// Initializes a new instance of the DeviceSelection class.
        /// </summary>
        public DeviceSelection() { }

        /// <summary>
        /// Initializes a new instance of the DeviceSelection class.
        /// </summary>
        public DeviceSelection(string shortId)
        {
            ShortId = shortId;
        }

        /// <summary>
        /// Identifier of the device selection
        /// </summary>
        [JsonProperty(PropertyName = "shortId")]
        public string ShortId { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (ShortId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ShortId");
            }
        }
    }
}
