// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DeviceFrameDefinition
    {
        /// <summary>
        /// Initializes a new instance of the DeviceFrameDefinition class.
        /// </summary>
        public DeviceFrameDefinition() { }

        /// <summary>
        /// Initializes a new instance of the DeviceFrameDefinition class.
        /// </summary>
        public DeviceFrameDefinition(double? width = default(double?), double? height = default(double?), string frameUrl = default(string), IList<double?> screen = default(IList<double?>))
        {
            Width = width;
            Height = height;
            FrameUrl = frameUrl;
            Screen = screen;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "width")]
        public double? Width { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public double? Height { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "frameUrl")]
        public string FrameUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "screen")]
        public IList<double?> Screen { get; set; }

    }
}
