// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// CPU data for device
    /// </summary>
    public partial class DeviceCpu
    {
        /// <summary>
        /// Initializes a new instance of the DeviceCpu class.
        /// </summary>
        public DeviceCpu() { }

        /// <summary>
        /// Initializes a new instance of the DeviceCpu class.
        /// </summary>
        public DeviceCpu(string frequency = default(string), string core = default(string))
        {
            Frequency = frequency;
            Core = core;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "frequency")]
        public string Frequency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "core")]
        public string Core { get; set; }

    }
}
