// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DeviceFrame
    {
        /// <summary>
        /// Initializes a new instance of the DeviceFrame class.
        /// </summary>
        public DeviceFrame() { }

        /// <summary>
        /// Initializes a new instance of the DeviceFrame class.
        /// </summary>
        public DeviceFrame(DeviceFrameDefinition grid = default(DeviceFrameDefinition), DeviceFrameDefinition full = default(DeviceFrameDefinition))
        {
            Grid = grid;
            Full = full;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "grid")]
        public DeviceFrameDefinition Grid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "full")]
        public DeviceFrameDefinition Full { get; set; }

    }
}
