// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Device screen resolution
    /// </summary>
    public partial class DeviceResolution
    {
        /// <summary>
        /// Initializes a new instance of the DeviceResolution class.
        /// </summary>
        public DeviceResolution() { }

        /// <summary>
        /// Initializes a new instance of the DeviceResolution class.
        /// </summary>
        public DeviceResolution(string height = default(string), string width = default(string), string ppi = default(string))
        {
            Height = height;
            Width = width;
            Ppi = ppi;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public string Height { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "width")]
        public string Width { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ppi")]
        public string Ppi { get; set; }

    }
}
