// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DistributionGroupUserGetResponse
    {
        /// <summary>
        /// Initializes a new instance of the DistributionGroupUserGetResponse
        /// class.
        /// </summary>
        public DistributionGroupUserGetResponse() { }

        /// <summary>
        /// Initializes a new instance of the DistributionGroupUserGetResponse
        /// class.
        /// </summary>
        public DistributionGroupUserGetResponse(string email, string id = default(string), string displayName = default(string), string name = default(string), string avatarUrl = default(string), bool? canChangePassword = default(bool?), bool? invitePending = default(bool?))
        {
            Id = id;
            Email = email;
            DisplayName = displayName;
            Name = name;
            AvatarUrl = avatarUrl;
            CanChangePassword = canChangePassword;
            InvitePending = invitePending;
        }

        /// <summary>
        /// The unique id (UUID) of the user
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// The email address of the user
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// The full name of the user. Might for example be first and last name
        /// </summary>
        [JsonProperty(PropertyName = "display_name")]
        public string DisplayName { get; set; }

        /// <summary>
        /// The unique name that is used to identify the user.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// The avatar URL of the user
        /// </summary>
        [JsonProperty(PropertyName = "avatar_url")]
        public string AvatarUrl { get; set; }

        /// <summary>
        /// User is required to send an old password in order to change the
        /// password.
        /// </summary>
        [JsonProperty(PropertyName = "can_change_password")]
        public bool? CanChangePassword { get; set; }

        /// <summary>
        /// Whether the has accepted the invite. Available when an invite is
        /// pending, and the value will be "true".
        /// </summary>
        [JsonProperty(PropertyName = "invite_pending")]
        public bool? InvitePending { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Email == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Email");
            }
        }
    }
}
