// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DistributionGroupUserRequest
    {
        /// <summary>
        /// Initializes a new instance of the DistributionGroupUserRequest
        /// class.
        /// </summary>
        public DistributionGroupUserRequest() { }

        /// <summary>
        /// Initializes a new instance of the DistributionGroupUserRequest
        /// class.
        /// </summary>
        public DistributionGroupUserRequest(IList<string> userIds = default(IList<string>), IList<string> userEmails = default(IList<string>))
        {
            UserIds = userIds;
            UserEmails = userEmails;
        }

        /// <summary>
        /// The list of unique ID (UUID) of the users
        /// </summary>
        [JsonProperty(PropertyName = "user_ids")]
        public IList<string> UserIds { get; set; }

        /// <summary>
        /// The list of emails of the users
        /// </summary>
        [JsonProperty(PropertyName = "user_emails")]
        public IList<string> UserEmails { get; set; }

    }
}
