// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DistributionGroup
    {
        /// <summary>
        /// Initializes a new instance of the DistributionGroup class.
        /// </summary>
        public DistributionGroup() { }

        /// <summary>
        /// Initializes a new instance of the DistributionGroup class.
        /// </summary>
        public DistributionGroup(string id = default(string), string name = default(string), bool? isLatest = default(bool?))
        {
            Id = id;
            Name = name;
            IsLatest = isLatest;
        }

        /// <summary>
        /// ID identifying a unique distribution group.
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// A name identifying a unique distribution group.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Is the containing release the latest one in this distribution
        /// group.
        /// </summary>
        [JsonProperty(PropertyName = "is_latest")]
        public bool? IsLatest { get; set; }

    }
}
