// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ErrorError
    {
        /// <summary>
        /// Initializes a new instance of the ErrorError class.
        /// </summary>
        public ErrorError() { }

        /// <summary>
        /// Initializes a new instance of the ErrorError class.
        /// </summary>
        public ErrorError(int? code = default(int?), string message = default(string))
        {
            Code = code;
            Message = message;
        }

        /// <summary>
        /// The status code return by the API. It can be 400 or 403 or 500.
        /// </summary>
        [JsonProperty(PropertyName = "code")]
        public int? Code { get; set; }

        /// <summary>
        /// The reason for the request failed
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
