// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EventCountPerSession
    {
        /// <summary>
        /// Initializes a new instance of the EventCountPerSession class.
        /// </summary>
        public EventCountPerSession() { }

        /// <summary>
        /// Initializes a new instance of the EventCountPerSession class.
        /// </summary>
        public EventCountPerSession(double? avgCountPerSession = default(double?), double? previousAvgCountPerSession = default(double?), IList<DateTimeDecimalCounts> countPerSession = default(IList<DateTimeDecimalCounts>))
        {
            AvgCountPerSession = avgCountPerSession;
            PreviousAvgCountPerSession = previousAvgCountPerSession;
            CountPerSession = countPerSession;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "avg_count_per_session")]
        public double? AvgCountPerSession { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "previous_avg_count_per_session")]
        public double? PreviousAvgCountPerSession { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "count_per_session")]
        public IList<DateTimeDecimalCounts> CountPerSession { get; set; }

    }
}
