// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EventDeviceCount
    {
        /// <summary>
        /// Initializes a new instance of the EventDeviceCount class.
        /// </summary>
        public EventDeviceCount() { }

        /// <summary>
        /// Initializes a new instance of the EventDeviceCount class.
        /// </summary>
        public EventDeviceCount(long? totalDevices = default(long?), long? totalDevicesWithEvent = default(long?), long? previousTotalDevicesWithEvent = default(long?), IList<DateTimeCounts> devicesCount = default(IList<DateTimeCounts>))
        {
            TotalDevices = totalDevices;
            TotalDevicesWithEvent = totalDevicesWithEvent;
            PreviousTotalDevicesWithEvent = previousTotalDevicesWithEvent;
            DevicesCount = devicesCount;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total_devices")]
        public long? TotalDevices { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total_devices_with_event")]
        public long? TotalDevicesWithEvent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "previous_total_devices_with_event")]
        public long? PreviousTotalDevicesWithEvent { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "devices_count")]
        public IList<DateTimeCounts> DevicesCount { get; set; }

    }
}
