// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// An event property value with counts
    /// </summary>
    public partial class EventPropertyValue
    {
        /// <summary>
        /// Initializes a new instance of the EventPropertyValue class.
        /// </summary>
        public EventPropertyValue() { }

        /// <summary>
        /// Initializes a new instance of the EventPropertyValue class.
        /// </summary>
        public EventPropertyValue(string name = default(string), long? count = default(long?), long? previousCount = default(long?))
        {
            Name = name;
            Count = count;
            PreviousCount = previousCount;
        }

        /// <summary>
        /// The event property value name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// The count of the the event property value
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long? Count { get; set; }

        /// <summary>
        /// The count of previous time range of the event property value
        /// </summary>
        [JsonProperty(PropertyName = "previous_count")]
        public long? PreviousCount { get; set; }

    }
}
