// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Event properties during the time range
    /// </summary>
    public partial class EventProperties
    {
        /// <summary>
        /// Initializes a new instance of the EventProperties class.
        /// </summary>
        public EventProperties() { }

        /// <summary>
        /// Initializes a new instance of the EventProperties class.
        /// </summary>
        public EventProperties(IList<string> eventPropertiesProperty = default(IList<string>))
        {
            EventPropertiesProperty = eventPropertiesProperty;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "event_properties")]
        public IList<string> EventPropertiesProperty { get; set; }

    }
}
