// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ImportDataContainer
    {
        /// <summary>
        /// Initializes a new instance of the ImportDataContainer class.
        /// </summary>
        public ImportDataContainer() { }

        /// <summary>
        /// Initializes a new instance of the ImportDataContainer class.
        /// </summary>
        public ImportDataContainer(string csvData = default(string))
        {
            CsvData = csvData;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "csvData")]
        public string CsvData { get; set; }

    }
}
