// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Build configuration when React Native, or other JavaScript tech, is
    /// part of the build steps
    /// </summary>
    public partial class JavaScriptBranchConfigurationProperties
    {
        /// <summary>
        /// Initializes a new instance of the
        /// JavaScriptBranchConfigurationProperties class.
        /// </summary>
        public JavaScriptBranchConfigurationProperties() { }

        /// <summary>
        /// Initializes a new instance of the
        /// JavaScriptBranchConfigurationProperties class.
        /// </summary>
        public JavaScriptBranchConfigurationProperties(string packageJsonPath)
        {
            PackageJsonPath = packageJsonPath;
        }

        /// <summary>
        /// Path to package.json file for the main project, e.g.
        /// "package.json" or "myapp/package.json"
        /// </summary>
        [JsonProperty(PropertyName = "packageJsonPath")]
        public string PackageJsonPath { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (PackageJsonPath == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PackageJsonPath");
            }
        }
    }
}
