// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Language
    {
        /// <summary>
        /// Initializes a new instance of the Language class.
        /// </summary>
        public Language() { }

        /// <summary>
        /// Initializes a new instance of the Language class.
        /// </summary>
        public Language(string languageName = default(string), long? count = default(long?), long? previousCount = default(long?))
        {
            LanguageName = languageName;
            Count = count;
            PreviousCount = previousCount;
        }

        /// <summary>
        /// language's name
        /// </summary>
        [JsonProperty(PropertyName = "language_name")]
        public string LanguageName { get; set; }

        /// <summary>
        /// count current of language
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public long? Count { get; set; }

        /// <summary>
        /// count of previous lanugage
        /// </summary>
        [JsonProperty(PropertyName = "previous_count")]
        public long? PreviousCount { get; set; }

    }
}
