// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Log
    {
        /// <summary>
        /// Initializes a new instance of the Log class.
        /// </summary>
        public Log() { }

        /// <summary>
        /// Initializes a new instance of the Log class.
        /// </summary>
        public Log(DateTime timestamp, Guid installId, Device device)
        {
            Timestamp = timestamp;
            InstallId = installId;
            Device = device;
        }

        /// <summary>
        /// Log creation timestamp.
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Install ID.
        /// </summary>
        [JsonProperty(PropertyName = "install_id")]
        public Guid InstallId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "device")]
        public Device Device { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Device == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Device");
            }
            if (this.Device != null)
            {
                this.Device.Validate();
            }
        }
    }
}
