// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A response containing information about the uploaded package.
    /// </summary>
    public partial class PackageUploadEndResponse
    {
        /// <summary>
        /// Initializes a new instance of the PackageUploadEndResponse class.
        /// </summary>
        public PackageUploadEndResponse() { }

        /// <summary>
        /// Initializes a new instance of the PackageUploadEndResponse class.
        /// </summary>
        public PackageUploadEndResponse(string packageUrl = default(string))
        {
            PackageUrl = packageUrl;
        }

        /// <summary>
        /// A URL to the new package. If upload was aborted will be null.
        /// </summary>
        [JsonProperty(PropertyName = "package_url")]
        public string PackageUrl { get; set; }

    }
}
