// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A request containing information for updating a package.
    /// </summary>
    public partial class PackageUpdateRequest
    {
        /// <summary>
        /// Initializes a new instance of the PackageUpdateRequest class.
        /// </summary>
        public PackageUpdateRequest() { }

        /// <summary>
        /// Initializes a new instance of the PackageUpdateRequest class.
        /// </summary>
        public PackageUpdateRequest(string distributionGroupName = default(string), string distributionGroupId = default(string), string releaseNotes = default(string))
        {
            DistributionGroupName = distributionGroupName;
            DistributionGroupId = distributionGroupId;
            ReleaseNotes = releaseNotes;
        }

        /// <summary>
        /// Name of a distribution group. The package will be associated with
        /// this distribution group. If the distribution group doesn't exist
        /// a 400 is returned. If both distribution group name and id are
        /// passed, the id is taking precedence.
        /// </summary>
        [JsonProperty(PropertyName = "distribution_group_name")]
        public string DistributionGroupName { get; set; }

        /// <summary>
        /// Id of a distribution group. The package will be associated with
        /// this distribution group. If the distribution group doesn't exist
        /// a 400 is returned. If both distribution group name and id are
        /// passed, the id is taking precedence.
        /// </summary>
        [JsonProperty(PropertyName = "distribution_group_id")]
        public string DistributionGroupId { get; set; }

        /// <summary>
        /// Release notes for this package.
        /// </summary>
        [JsonProperty(PropertyName = "release_notes")]
        public string ReleaseNotes { get; set; }

    }
}
