// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Places and count during the time range in descending order
    /// </summary>
    public partial class Places
    {
        /// <summary>
        /// Initializes a new instance of the Places class.
        /// </summary>
        public Places() { }

        /// <summary>
        /// Initializes a new instance of the Places class.
        /// </summary>
        public Places(long? total = default(long?), IList<Place> placesProperty = default(IList<Place>))
        {
            Total = total;
            PlacesProperty = placesProperty;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public long? Total { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "places")]
        public IList<Place> PlacesProperty { get; set; }

    }
}
