// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A response containing information pertaining to starting a release
    /// upload process
    /// </summary>
    public partial class ReleaseUploadBeginResponse
    {
        /// <summary>
        /// Initializes a new instance of the ReleaseUploadBeginResponse class.
        /// </summary>
        public ReleaseUploadBeginResponse() { }

        /// <summary>
        /// Initializes a new instance of the ReleaseUploadBeginResponse class.
        /// </summary>
        public ReleaseUploadBeginResponse(string uploadId, string uploadUrl)
        {
            UploadId = uploadId;
            UploadUrl = uploadUrl;
        }

        /// <summary>
        /// The ID for the current upload
        /// </summary>
        [JsonProperty(PropertyName = "upload_id")]
        public string UploadId { get; set; }

        /// <summary>
        /// The URL where the client needs to upload the release to
        /// </summary>
        [JsonProperty(PropertyName = "upload_url")]
        public string UploadUrl { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (UploadId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UploadId");
            }
            if (UploadUrl == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UploadUrl");
            }
        }
    }
}
