// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SessionsPerDevice
    {
        /// <summary>
        /// Initializes a new instance of the SessionsPerDevice class.
        /// </summary>
        public SessionsPerDevice() { }

        /// <summary>
        /// Initializes a new instance of the SessionsPerDevice class.
        /// </summary>
        public SessionsPerDevice(double? averageSessionsPerUser = default(double?), double? previousAverageSessionsPerUser = default(double?), long? totalCount = default(long?), long? previousTotalCount = default(long?), IList<SessionsPerDeviceSessionsPerUserItem> sessionsPerUser = default(IList<SessionsPerDeviceSessionsPerUserItem>))
        {
            AverageSessionsPerUser = averageSessionsPerUser;
            PreviousAverageSessionsPerUser = previousAverageSessionsPerUser;
            TotalCount = totalCount;
            PreviousTotalCount = previousTotalCount;
            SessionsPerUser = sessionsPerUser;
        }

        /// <summary>
        /// average seesion per user
        /// </summary>
        [JsonProperty(PropertyName = "average_sessions_per_user")]
        public double? AverageSessionsPerUser { get; set; }

        /// <summary>
        /// previous average session per user
        /// </summary>
        [JsonProperty(PropertyName = "previous_average_sessions_per_user")]
        public double? PreviousAverageSessionsPerUser { get; set; }

        /// <summary>
        /// total session per device count
        /// </summary>
        [JsonProperty(PropertyName = "total_count")]
        public long? TotalCount { get; set; }

        /// <summary>
        /// previous total count
        /// </summary>
        [JsonProperty(PropertyName = "previous_total_count")]
        public long? PreviousTotalCount { get; set; }

        /// <summary>
        /// the session count for each interval per device
        /// </summary>
        [JsonProperty(PropertyName = "sessions_per_user")]
        public IList<SessionsPerDeviceSessionsPerUserItem> SessionsPerUser { get; set; }

    }
}
