// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SessionDurationsDistributionDistributionItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SessionDurationsDistributionDistributionItem class.
        /// </summary>
        public SessionDurationsDistributionDistributionItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// SessionDurationsDistributionDistributionItem class.
        /// </summary>
        public SessionDurationsDistributionDistributionItem(string bucket = default(string), int? count = default(int?))
        {
            Bucket = bucket;
            Count = count;
        }

        /// <summary>
        /// the bucket name
        /// </summary>
        [JsonProperty(PropertyName = "bucket")]
        public string Bucket { get; set; }

        /// <summary>
        /// the count of sessions in current bucket
        /// </summary>
        [JsonProperty(PropertyName = "count")]
        public int? Count { get; set; }

    }
}
