// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SessionCounts
    {
        /// <summary>
        /// Initializes a new instance of the SessionCounts class.
        /// </summary>
        public SessionCounts() { }

        /// <summary>
        /// Initializes a new instance of the SessionCounts class.
        /// </summary>
        public SessionCounts(long? totalCount = default(long?), long? previousTotalCount = default(long?), IList<DateTimeCounts> sessions = default(IList<DateTimeCounts>))
        {
            TotalCount = totalCount;
            PreviousTotalCount = previousTotalCount;
            Sessions = sessions;
        }

        /// <summary>
        /// total session count
        /// </summary>
        [JsonProperty(PropertyName = "total_count")]
        public long? TotalCount { get; set; }

        /// <summary>
        /// previous total session count
        /// </summary>
        [JsonProperty(PropertyName = "previous_total_count")]
        public long? PreviousTotalCount { get; set; }

        /// <summary>
        /// the total session count for each interval
        /// </summary>
        [JsonProperty(PropertyName = "sessions")]
        public IList<DateTimeCounts> Sessions { get; set; }

    }
}
