// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The source repository
    /// </summary>
    public partial class SourceRepository
    {
        /// <summary>
        /// Initializes a new instance of the SourceRepository class.
        /// </summary>
        public SourceRepository() { }

        /// <summary>
        /// Initializes a new instance of the SourceRepository class.
        /// </summary>
        public SourceRepository(string name = default(string))
        {
            Name = name;
        }

        /// <summary>
        /// The repository name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

    }
}
