// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Status
    {
        /// <summary>
        /// Initializes a new instance of the Status class.
        /// </summary>
        public Status() { }

        /// <summary>
        /// Initializes a new instance of the Status class.
        /// </summary>
        public Status(string statusProperty)
        {
            StatusProperty = statusProperty;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string StatusProperty { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (StatusProperty == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "StatusProperty");
            }
        }
    }
}
