// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Subscription information
    /// </summary>
    public partial class Subscription
    {
        /// <summary>
        /// Initializes a new instance of the Subscription class.
        /// </summary>
        public Subscription() { }

        /// <summary>
        /// Initializes a new instance of the Subscription class.
        /// </summary>
        public Subscription(string startsAt = default(string), string endsAt = default(string), double? daysLeft = default(double?), Tier tier = default(Tier), bool? active = default(bool?), Guid? id = default(Guid?))
        {
            StartsAt = startsAt;
            EndsAt = endsAt;
            DaysLeft = daysLeft;
            Tier = tier;
            Active = active;
            Id = id;
        }

        /// <summary>
        /// The date the subscription began
        /// </summary>
        [JsonProperty(PropertyName = "startsAt")]
        public string StartsAt { get; set; }

        /// <summary>
        /// The date the subscription will end or ended
        /// </summary>
        [JsonProperty(PropertyName = "endsAt")]
        public string EndsAt { get; set; }

        /// <summary>
        /// The number of days left in the subscription
        /// </summary>
        [JsonProperty(PropertyName = "daysLeft")]
        public double? DaysLeft { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tier")]
        public Tier Tier { get; set; }

        /// <summary>
        /// Is the subscription currently active?
        /// </summary>
        [JsonProperty(PropertyName = "active")]
        public bool? Active { get; set; }

        /// <summary>
        /// Id of the subscription
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public Guid? Id { get; set; }

    }
}
