// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A request containing information pertaining to starting a symbol
    /// upload process
    /// </summary>
    public partial class SymbolUploadBeginRequest
    {
        /// <summary>
        /// Initializes a new instance of the SymbolUploadBeginRequest class.
        /// </summary>
        public SymbolUploadBeginRequest() { }

        /// <summary>
        /// Initializes a new instance of the SymbolUploadBeginRequest class.
        /// </summary>
        public SymbolUploadBeginRequest(string clientCallback = default(string))
        {
            ClientCallback = clientCallback;
        }
        /// <summary>
        /// Static constructor for SymbolUploadBeginRequest class.
        /// </summary>
        static SymbolUploadBeginRequest()
        {
            SymbolType = "Apple";
        }

        /// <summary>
        /// The callback URL that the client can optionally provide to get
        /// status updates for the current symbol upload
        /// </summary>
        [JsonProperty(PropertyName = "client_callback")]
        public string ClientCallback { get; set; }

        /// <summary>
        /// The type of the symbol for the current symbol upload
        /// </summary>
        [JsonProperty(PropertyName = "symbol_type")]
        public static string SymbolType { get; private set; }

    }
}
