// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TableColumn
    {
        /// <summary>
        /// Initializes a new instance of the TableColumn class.
        /// </summary>
        public TableColumn() { }

        /// <summary>
        /// Initializes a new instance of the TableColumn class.
        /// </summary>
        public TableColumn(string name = default(string), bool? isIndexed = default(bool?), string type = default(string), bool? canDelete = default(bool?), bool? canUpdateIndex = default(bool?))
        {
            Name = name;
            IsIndexed = isIndexed;
            Type = type;
            CanDelete = canDelete;
            CanUpdateIndex = canUpdateIndex;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsIndexed")]
        public bool? IsIndexed { get; set; }

        /// <summary>
        /// Possible values include: 'String', 'Boolean', 'Number', 'Date',
        /// 'Version', 'Custom'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CanDelete")]
        public bool? CanDelete { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CanUpdateIndex")]
        public bool? CanUpdateIndex { get; set; }

    }
}
