// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Options required to start the test run
    /// </summary>
    public partial class TestCloudStartTestRunOptions
    {
        /// <summary>
        /// Initializes a new instance of the TestCloudStartTestRunOptions
        /// class.
        /// </summary>
        public TestCloudStartTestRunOptions() { }

        /// <summary>
        /// Initializes a new instance of the TestCloudStartTestRunOptions
        /// class.
        /// </summary>
        public TestCloudStartTestRunOptions(string testFramework, string deviceSelection, string locale = default(string), string testSeries = default(string), object testParameters = default(object))
        {
            TestFramework = testFramework;
            DeviceSelection = deviceSelection;
            Locale = locale;
            TestSeries = testSeries;
            TestParameters = testParameters;
        }

        /// <summary>
        /// Test framework used by tests.
        /// </summary>
        [JsonProperty(PropertyName = "test_framework")]
        public string TestFramework { get; set; }

        /// <summary>
        /// Device selection string.
        /// </summary>
        [JsonProperty(PropertyName = "device_selection")]
        public string DeviceSelection { get; set; }

        /// <summary>
        /// Locale that should be used to run tests.
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// Name of the test series.
        /// </summary>
        [JsonProperty(PropertyName = "test_series")]
        public string TestSeries { get; set; }

        /// <summary>
        /// A JSON dictionary with additional test parameters
        /// </summary>
        [JsonProperty(PropertyName = "test_parameters")]
        public object TestParameters { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (TestFramework == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "TestFramework");
            }
            if (DeviceSelection == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "DeviceSelection");
            }
        }
    }
}
