// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TestReportFeaturesItemTestsItemRunsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TestReportFeaturesItemTestsItemRunsItem class.
        /// </summary>
        public TestReportFeaturesItemTestsItemRunsItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TestReportFeaturesItemTestsItemRunsItem class.
        /// </summary>
        public TestReportFeaturesItemTestsItemRunsItem(double? number = default(double?), IList<TestReportFeaturesItemTestsItemRunsItemStepsItem> steps = default(IList<TestReportFeaturesItemTestsItemRunsItemStepsItem>), double? failed = default(double?), double? skipped = default(double?))
        {
            Number = number;
            Steps = steps;
            Failed = failed;
            Skipped = skipped;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public double? Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "steps")]
        public IList<TestReportFeaturesItemTestsItemRunsItemStepsItem> Steps { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "failed")]
        public double? Failed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "skipped")]
        public double? Skipped { get; set; }

    }
}
