// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Defines headers for startUploadingFile operation.
    /// </summary>
    public partial class TestStartUploadingFileHeaders
    {
        /// <summary>
        /// Initializes a new instance of the TestStartUploadingFileHeaders
        /// class.
        /// </summary>
        public TestStartUploadingFileHeaders() { }

        /// <summary>
        /// Initializes a new instance of the TestStartUploadingFileHeaders
        /// class.
        /// </summary>
        public TestStartUploadingFileHeaders(string location = default(string))
        {
            Location = location;
        }

        /// <summary>
        /// Relative URL that points to the upload endpoint
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

    }
}
