// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Most important information about a test run.
    /// </summary>
    public partial class TestRunSummary
    {
        /// <summary>
        /// Initializes a new instance of the TestRunSummary class.
        /// </summary>
        public TestRunSummary() { }

        /// <summary>
        /// Initializes a new instance of the TestRunSummary class.
        /// </summary>
        public TestRunSummary(string date = default(string), string statusDescription = default(string), double? failed = default(double?), double? passed = default(double?), bool? completed = default(bool?))
        {
            Date = date;
            StatusDescription = statusDescription;
            Failed = failed;
            Passed = passed;
            Completed = completed;
        }

        /// <summary>
        /// Date of the test run.
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public string Date { get; set; }

        /// <summary>
        /// Human-readable status of the test run.
        /// </summary>
        [JsonProperty(PropertyName = "statusDescription")]
        public string StatusDescription { get; set; }

        /// <summary>
        /// Number of failed tests
        /// </summary>
        [JsonProperty(PropertyName = "failed")]
        public double? Failed { get; set; }

        /// <summary>
        /// Number of passed tests
        /// </summary>
        [JsonProperty(PropertyName = "passed")]
        public double? Passed { get; set; }

        /// <summary>
        /// Tells whether the test run has completed
        /// </summary>
        [JsonProperty(PropertyName = "completed")]
        public bool? Completed { get; set; }

    }
}
