// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TestReportFeaturesItemTestsItemRunsItemStepsItemStepExecutionsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// TestReportFeaturesItemTestsItemRunsItemStepsItemStepExecutionsItem
        /// class.
        /// </summary>
        public TestReportFeaturesItemTestsItemRunsItemStepsItemStepExecutionsItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// TestReportFeaturesItemTestsItemRunsItemStepsItemStepExecutionsItem
        /// class.
        /// </summary>
        public TestReportFeaturesItemTestsItemRunsItemStepsItemStepExecutionsItem(string deviceSnapshotId = default(string), string status = default(string), double? timestamp = default(double?))
        {
            DeviceSnapshotId = deviceSnapshotId;
            Status = status;
            Timestamp = timestamp;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "device_snapshot_id")]
        public string DeviceSnapshotId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public double? Timestamp { get; set; }

    }
}
