// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UserUpdateRequest
    {
        /// <summary>
        /// Initializes a new instance of the UserUpdateRequest class.
        /// </summary>
        public UserUpdateRequest() { }

        /// <summary>
        /// Initializes a new instance of the UserUpdateRequest class.
        /// </summary>
        public UserUpdateRequest(string displayName = default(string))
        {
            DisplayName = displayName;
        }

        /// <summary>
        /// The full name of the user. Might for example be first and last name
        /// </summary>
        [JsonProperty(PropertyName = "display_name")]
        public string DisplayName { get; set; }

    }
}
