// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Versions
    {
        /// <summary>
        /// Initializes a new instance of the Versions class.
        /// </summary>
        public Versions() { }

        /// <summary>
        /// Initializes a new instance of the Versions class.
        /// </summary>
        public Versions(IList<Version> versionsProperty = default(IList<Version>), long? total = default(long?))
        {
            VersionsProperty = versionsProperty;
            Total = total;
        }

        /// <summary>
        /// list of version count
        /// </summary>
        [JsonProperty(PropertyName = "versions")]
        public IList<Version> VersionsProperty { get; set; }

        /// <summary>
        /// the total count of versions
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public long? Total { get; set; }

    }
}
