// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class WaitlistApproveRequest
    {
        /// <summary>
        /// Initializes a new instance of the WaitlistApproveRequest class.
        /// </summary>
        public WaitlistApproveRequest() { }

        /// <summary>
        /// Initializes a new instance of the WaitlistApproveRequest class.
        /// </summary>
        public WaitlistApproveRequest(IList<string> emailAddresses)
        {
            EmailAddresses = emailAddresses;
        }

        /// <summary>
        /// The list of email addresses to approve
        /// </summary>
        [JsonProperty(PropertyName = "email_addresses")]
        public IList<string> EmailAddresses { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (EmailAddresses == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "EmailAddresses");
            }
        }
    }
}
