// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class WaitListItemResponse
    {
        /// <summary>
        /// Initializes a new instance of the WaitListItemResponse class.
        /// </summary>
        public WaitListItemResponse() { }

        /// <summary>
        /// Initializes a new instance of the WaitListItemResponse class.
        /// </summary>
        public WaitListItemResponse(string email, bool didSucceed, string message = default(string))
        {
            Email = email;
            DidSucceed = didSucceed;
            Message = message;
        }

        /// <summary>
        /// The email address to invite
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Indicates whether inviting the user succeeded
        /// </summary>
        [JsonProperty(PropertyName = "did_succeed")]
        public bool DidSucceed { get; set; }

        /// <summary>
        /// Details about the result for this invitee
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Email == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Email");
            }
        }
    }
}
