// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class XamarinSolution
    {
        /// <summary>
        /// Initializes a new instance of the XamarinSolution class.
        /// </summary>
        public XamarinSolution() { }

        /// <summary>
        /// Initializes a new instance of the XamarinSolution class.
        /// </summary>
        public XamarinSolution(string path, IList<string> configurations)
        {
            Path = path;
            Configurations = configurations;
        }

        /// <summary>
        /// Path to solution
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; set; }

        /// <summary>
        /// Solution configurations
        /// </summary>
        [JsonProperty(PropertyName = "configurations")]
        public IList<string> Configurations { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Path == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Path");
            }
            if (Configurations == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Configurations");
            }
        }
    }
}
