// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NomadCode.MobileCenter.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class XcodeScheme
    {
        /// <summary>
        /// Initializes a new instance of the XcodeScheme class.
        /// </summary>
        public XcodeScheme() { }

        /// <summary>
        /// Initializes a new instance of the XcodeScheme class.
        /// </summary>
        public XcodeScheme(string name, bool hasTestAction)
        {
            Name = name;
            HasTestAction = hasTestAction;
        }

        /// <summary>
        /// Scheme name
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Does scheme have a test action?
        /// </summary>
        [JsonProperty(PropertyName = "hasTestAction")]
        public bool HasTestAction { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
        }
    }
}
